services:
  api:
    build: .
    container_name: ai-kb-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: ai-kb-frontend
    ports:
      - "8501:8501" 
    depends_on:
      - api 

  mongo:
    image: mongo:7
    container_name: ai-kb-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: